./bin/acotsp --simple \
            -f benchmarks/darkVUTinverted-256-stipple.tsp \
            -i 150 \
            -m 10 \
            -p 0.01 \
            -q 0.5 \
            -r 0.03 \
            -b 4 \
            -a 1 \
